name: TPAccept
main: TStark\TPAcceptForm\Main
version: 1.1.0
api: 5.0.0
author: §bT. Stark
description: §6Advanced TP application system with interactive forms
website: §ahttps://minecraftpetools.netlify.app

commands:
  tpa:
    description: "Send a teleport request to a player"
    usage: "/tpa <player>"
    permission: "tpaform.command.tpa"
  tpacancel:
    description: "Cancel your pending teleport request"
    usage: "/tpacancel <player>"
    permission: "tpaform.command.tpacancel"
  tptoggle:
    description: "Toggle teleport requests on/off"
    usage: "/tptoggle"
    permission: "tpaform.command.tptoggle"

permissions:
  tpaform.command.tpa:
    description: "Allows using the tpa command"
    default: true
  tpaform.command.tpacancel:
    description: "Allows using the tpacancel command"
    default: true
  tpaform.command.tptoggle:
    description: "Allows using the tptoggle command"
    default: true
  tpaform.bypass:
    description: "Bypass teleport request restrictions"
    default: op
